### ISSUE TITLE
File manifest

### ISSUE THREAD

**Issue by lathannspell** [Mgamerz/AlotAddOnGUI#11]
There seems to be a problem with ALOT installer. After updating the program, an info pops up, there is an 'error reading file manifest'
[alotinstaller-20180508.txt](https://github.com/Mgamerz/AlotAddOnGUI/files/1984852/alotinstaller-20180508.txt)

**Comment by Mgamerz** [comment]
Yes I know what the issue is but I have not had time to fix it yet. I will be working on it later today, for a quick fix you will need to change locales to one that uses a decimal point rather than a command for fractional numbers (1.1 instead of 1,1).

**Comment by Mgamerz** [comment]
The beta mode should now pull an update that fixes this, please opt into
beta mode and let me know if it works.

**Comment by Mgamerz** [comment]
This issue has been fixed in the latest stable release and was fixed by commit cc44f27d740797d89472d95b6d94828856532df7.
