### ISSUE TITLE
You are missing quite some ME1 fixes

### ISSUE THREAD

**Issue by mirh** [Mgamerz/AlotAddOnGUI#17]
e74561aa7c0e8467eda08119c42d1d1329f8cf05
5e3eaf187308f7ce8d4e4fa20e5ef3a408010d83

I'm not sure what you are doing with the AGEIA registry keys, but the actually proper fix is to install [legacy physx](https://www.nvidia.com/en-us/drivers/physx/physx-9-13-0604-legacy-driver/), and remove the dreaded enableLocalPhysXCore key (or well, at least I know no reason to use the old libs)
Similarly, you aren't going much further with just removing XP compatibility. Since W8.1 you also need to add the RUNASINVOKER flag to finally eradicate the administrator request curse. 

Also, I never had sound problems *to be fair*.. But if that is your concern at least the first basic step should be to have people use updated OpenAL.

**Comment by Mgamerz** [comment]
Ageia key is to remove run as admin requirement.

XP key removal is to undo user settings that would force run as admin on
top of the already windows database. We have had this problem solved for
years now.

**Comment by Mgamerz** [comment]
Also run as invoker does not work for Mass effect 1. This whole thing has
been documented already
https://me3tweaks.mgamerzproductions.com/2018/01/why-mass-effect-requires-administrator.html

**Comment by mirh** [comment]
> Ageia key is to remove run as admin requirement.

It is only needed if you haven't the physx runtime installed. 
And while I can't claim to know of any actual improvement between 2.7.2.5 and 2.7.2.9 (nor why the physx sdk required at all this *EpicLocalDLLHack*) it simply seems the proper way to do it. 

> We have had this problem solved for years now.

I have literally met people that got screwed by the ALOT installer this week. 

> Also run as invoker does not work for Mass effect 1. 

If it doesn't work it is probably because you are forcing it in HKLM rather than HKCU. People on steam don't report issues with it.

**Comment by Mgamerz** [comment]
Then you refer them to the support discord, because we have seen no users
with this issue for years.

**Comment by mirh** [comment]
Do you understand that stupid key isn't just a ME thing and it is breaking [other games](https://web.archive.org/web/20170518141257/http://forums.steampowered.com/forums/showthread.php?t=786523&page=3#post21432065)?

**Comment by Mgamerz** [comment]
This is a problem with the game. Not ALOT Installer. We are not going to be
installing additional software for the user which may or may not cause
additional further problems. This is a texture installer, not a bugfix mod.

**Comment by mirh** [comment]
Lol? The texture installer seems to do way more than that actually to be fair. 
And it's not about "may or may not". This simply isn't the right way to do it, and having to write a separate program to grant permissions should be a big alarm bell to that.  

If you don't want to bundle a whole *19MB* installer inside a 4GB one, whatever, but at least throw something, anything, inside C:\Program Files (x86)\NVIDIA Corporation\PhysX\Engine\v2.7.2 (or whatever the value in `HKLM\SOFTWARE\Wow6432Node\AGEIA Technologies\PhysXCore Path` is). 
If you can't ***even*** be bothered to cherry pick the right dlls from the installer, at least just copy PhysXCore.dll from ME's installation folder.

**Comment by Mgamerz** [comment]
This is not a problem with alot installer nor is it one caused by it. This is a problem with the game executable itself.

 End of discussion.
