### ISSUE TITLE
ALOT v11 still has v10 manifest?

### ISSUE THREAD

**Issue by cmeeren** [Mgamerz/AlotAddOnGUI#20]
I downloaded ALOT v11 for ME1 (`ALOT for ME1 11.0-83-2020-11-1591229529.zip`). When I open it, it only lists and recognizes v10 files, not v11. Same for ALOV, it only recognizes 1.1, not 2.1.

![image](https://user-images.githubusercontent.com/7766733/87279727-94c01480-c4f1-11ea-9b75-b9148deebd9b.png)

**Comment by cmeeren** [comment]
I downloaded the installer here from GH, seems to work. The wrong version seems to be uploaded to Nexus.

**Comment by starkgate** [comment]
The manifest auto updates, the version on Nexus doesn't matter

**Comment by cmeeren** [comment]
Ok, there was an error updating also. No idea what caused that.
