### ISSUE TITLE
Add a manifest tag to resize textures

### ISSUE THREAD

**Issue by starkgate** [Mgamerz/AlotAddOnGUI#21]
This would be useful to downscale 4K norms in addons to 2K.

**Comment by Mgamerz** [comment]
You would need to specify how this would work in the manifest.

**Comment by starkgate** [comment]
I think it'd only be needed for texture packagefiles. Something like this:

```
<packagefile me2="true" sourcename="MASSEFFECT3.EXE_0x738FAA8B.dds" destinationname="WPN_BLSb_Diff_0xA56179D6.dds" resolution="2048" />
```

I think the special case of non-square textures is rare enough that we don't need to specify X and Y resolution, but something like "2048,2048" would also work.

**Comment by Mgamerz** [comment]
How would this work when building the add-on? The textures are stored in
their entirety with all mips. How would mem know to drop the 4K mip?

**Comment by starkgate** [comment]
The list of textures to be downscaled would be sent to MEM before installation, MEM would store it somewhere and downscale any textures it receives afterwards that match the list accordingly. I know aquadran said recently he wasn't interested in adding features to MEM anymore. However, doing it from the installer would be infeasible.

Here's a screenshot from the discussion I had with aquadran in November. My original suggestion was to have a secondary manifest with a list of textures to be downscaled. To summarise, I see two ways of achieving our results:

- Individually tag all textures that need to be downscaled within the manifest's addonfile nodes
`<packagefile me2="true" sourcename="MASSEFFECT3.EXE_0x738FAA8B.dds" destinationname="WPN_BLSb_Diff_0xA56179D6.dds" resolution="2048" />`
- Bulk downscale any texture that matches a file name pattern within a new manifest node
```
<resize><!-- Hash list sent to MEM at installation -->
  <texture name="HM*Norm" maxresolution="2048" /><!-- Resize settings for a regex pattern. "maxresolution" means any texture already smaller than 2048 won't be resized. This would be the most useful setting since we could simply "blacklist" many of the norms at once -->
  <texture hash="0x12345678" maxresolution="1024" /><!-- Resize based on a hash -->
  <texture hash="0xA56179D6.dds" resolution="2048" /><!-- Basically the equivalent of the first option, but outside the addonfile nodes -->
</resize>
```

![Screenshot_2020-07-21_08-23-29](https://user-images.githubusercontent.com/12874678/88020153-7f6b6b80-cb2b-11ea-88ed-3847e21a2737.png)

**Comment by Mgamerz** [comment]
It seems like this would be better handled before installation time, no?
Like the textures should be downscaled during the staging process when all
the textutes are still loose files. Possibly during addon build step.

**Comment by Mgamerz** [comment]
aquadran added automatic dropping of 4K mips for norms in a recent update to MEM, so I'm closing this issue.
