### ISSUE TITLE
Ashley Complexion Tweak Entry Incorrect, Not Working

### ISSUE THREAD

**Issue by ProjectSynchro** [Mgamerz/AlotAddOnGUI#9]
The "Ashley Complexion Tweak " entry in the Ellise Section of the installer looks for a filename of "el_Ashley Complexion Tweak.7z-569-1-0.7z" while the download section of Ellise's mod page shows a filename of "el_AshComplexionTweak.7z-569-1-0.7z". Renaming does not rectify the issue.

The Download Assistant then refuses to import it and as far as the user can tell it isn't there.
This isn't game breaking, and this can be bypassed by the "User Addon" portion of the installer but this is an issue with the manifest for sure.

EDIT: see other post

![image](https://user-images.githubusercontent.com/5131712/39445239-65a6e2f2-4c88-11e8-9ed6-21ee48407a49.png)

Should add..
I am running the latest release version and the manifest is up to date as far as I can tell.

**Comment by ProjectSynchro** [comment]
Should add,
I am running the latest release version and the manifest is up to date as far as I can tell.

**Comment by ProjectSynchro** [comment]
Adding on to this
Add a more clear description of the link needed to download as this is completely avoidable with better documentation.

For those with the same issue: the "Ash Complexion Tweak - .MEM" file is the one you want to get.

Should close this thread

**Comment by Mgamerz** [comment]
The pop-up shows it is called .MEM when you click download.

**Comment by ProjectSynchro** [comment]
Odd, was not getting any popups, therefore why I was having issues with it.
Not that it's a huge glaring issue, simply just needs more clarification imo.

EDIT: Scratch that, I get the notification if check my toasts in Windows 10, still reads the incorrect name.

![tempscreenshot](https://user-images.githubusercontent.com/5131712/39450146-4fa37b90-4c98-11e8-9188-94cfef51c978.png)

**Comment by Mgamerz** [comment]
We will look into fixing this, I see your pull request and I'm talking it over with the other devs.
